# Generated by Django 3.1.7 on 2021-04-01 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255)),
                ('mobile_no', models.CharField(max_length=10)),
                ('email_id', models.EmailField(blank=True, max_length=255)),
                ('ret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255)),
                ('mobile_no', models.CharField(max_length=10)),
                ('email_id', models.EmailField(blank=True, max_length=255)),
                ('ret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payment_mode', models.CharField(choices=[('1', 'Cash'), ('2', 'Card'), ('3', 'UPI'), ('4', 'Other Online Mode')], max_length=50)),
                ('payment_status', models.CharField(choices=[('1', 'Pending'), ('2', 'Received')], max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumbocashapi.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payment_mode', models.CharField(choices=[('1', 'Cash'), ('2', 'Card'), ('3', 'UPI'), ('4', 'Other Online Mode')], max_length=50)),
                ('payment_status', models.CharField(choices=[('1', 'Pending'), ('2', 'Paid')], max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumbocashapi.supplier')),
            ],
        ),
    ]
