# Generated by Django 3.1.7 on 2021-03-12 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jumbocashapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('ret_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('ret_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(choices=[(1, 'Cash'), (2, 'Card'), (3, 'UPI'), (4, 'Other Online Mode')], max_length=50)),
                ('payment_status', models.CharField(choices=[(1, 'Pending'), (2, 'Received')], max_length=50)),
                ('due_date', models.DateField(blank=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumbocashapi.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(choices=[(1, 'Cash'), (2, 'Card'), (3, 'UPI'), (4, 'Other Online Mode')], max_length=50)),
                ('payment_status', models.CharField(choices=[(1, 'Pending'), (2, 'Paid')], max_length=50)),
                ('due_date', models.DateField(blank=True)),
                ('sup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumbocashapi.supplier')),
            ],
        ),
    ]
