# Generated by Django 3.1.7 on 2021-04-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumbocashapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
