# Generated by Django 3.1.7 on 2021-03-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumbocashapi', '0002_customer_expensetransaction_incometransaction_supplier'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_id',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
