# Generated by Django 3.1.7 on 2021-03-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumbocashapi', '0003_auto_20210312_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email_id',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='lastname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
