# Generated by Django 3.1.7 on 2021-03-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumbocashapi', '0004_auto_20210312_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='payment_mode',
            field=models.CharField(choices=[('1', 'Cash'), ('2', 'Card'), ('3', 'UPI'), ('4', 'Other Online Mode')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='payment_status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Paid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='payment_mode',
            field=models.CharField(choices=[('1', 'Cash'), ('2', 'Card'), ('3', 'UPI'), ('4', 'Other Online Mode')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='payment_status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Received')], max_length=50),
        ),
    ]
