# Generated by Django 3.1.7 on 2021-03-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumbocashapi', '0006_auto_20210312_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='lastname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
