# Generated by Django 3.1.7 on 2021-03-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumbocashapi', '0007_auto_20210325_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='mobile_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
