# Generated by Django 3.1.7 on 2021-03-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumbocashapi', '0008_auto_20210325_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ret_id',
            new_name='ret',
        ),
    ]
