# Generated by Django 3.1.7 on 2021-03-26 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumbocashapi', '0010_auto_20210326_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensetransaction',
            old_name='sup',
            new_name='sup_id',
        ),
        migrations.RenameField(
            model_name='incometransaction',
            old_name='cust',
            new_name='cust_id',
        ),
    ]
