# Generated by Django 3.1.7 on 2021-03-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumbocashapi', '0011_auto_20210326_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='email_id',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mobile_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
